
name: Run NYC Taxi Data Pipeline

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type YES to run the full pipeline"
        required: true

jobs:
  run_pipeline:
    if: github.event.inputs.confirm == 'YES'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-2"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main pipeline
        run: |
          python main_pipeline.py

      - name: Upload logs as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
